# Multi-stage build for kotacom frontend (Next.js 16 + Sanity monorepo).
# Builds only the `frontend` workspace and runs `next start`.
# Dokploy passes app env as --build-arg; ARG/ENV pairs make them visible to `next build`.

# ---- Builder ----
FROM node:22-alpine AS builder
WORKDIR /app

# Install pnpm 10.19.0
RUN corepack enable && corepack prepare pnpm@10.19.0 --activate

# Build-time env vars (injected by Dokploy as build args)
ARG AI_GATEWAY_API_KEY
ARG AI_WRITER_ACTION_SECRET
ARG AI_WRITER_ALLOWED_ORIGINS
ARG AI_WRITER_GEMINI_KEYS
ARG AI_WRITER_GROQ_KEYS
ARG NEXT_PUBLIC_SANITY_API_VERSION
ARG NEXT_PUBLIC_SANITY_DATASET
ARG NEXT_PUBLIC_SANITY_PROJECT_ID
ARG NEXT_PUBLIC_SITE_ENV
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_STUDIO_URL
ARG NEXT_RESEND_FROM_EMAIL
ARG NEXT_RESEND_TO_EMAIL
ARG NX_DAEMON
ARG RESEND_API_KEY
ARG REVALIDATE_SECRET
ARG SANITY_API_READ_TOKEN
ARG SANITY_AUTH_TOKEN
ARG SANITY_DEPLOY
ARG SANITY_DEV
ARG SANITY_STUDIO_API_VERSION
ARG SANITY_STUDIO_APP_ID
ARG SANITY_STUDIO_DATASET
ARG SANITY_STUDIO_HOSTNAME
ARG SANITY_STUDIO_PREVIEW_URL
ARG SANITY_STUDIO_PROJECT_ID
ARG SEO_DASHBOARD_PASSWORD
ARG SEO_SESSION_SECRET
ARG SEO_SETTINGS_ENCRYPTION_KEY
ARG TURBO_CACHE
ARG TURBO_DOWNLOAD_LOCAL_ENABLED
ARG TURBO_REMOTE_ONLY
ARG TURBO_RUN_SUMMARY

ENV AI_GATEWAY_API_KEY=$AI_GATEWAY_API_KEY
ENV AI_WRITER_ACTION_SECRET=$AI_WRITER_ACTION_SECRET
ENV AI_WRITER_ALLOWED_ORIGINS=$AI_WRITER_ALLOWED_ORIGINS
ENV AI_WRITER_GEMINI_KEYS=$AI_WRITER_GEMINI_KEYS
ENV AI_WRITER_GROQ_KEYS=$AI_WRITER_GROQ_KEYS
ENV NEXT_PUBLIC_SANITY_API_VERSION=$NEXT_PUBLIC_SANITY_API_VERSION
ENV NEXT_PUBLIC_SANITY_DATASET=$NEXT_PUBLIC_SANITY_DATASET
ENV NEXT_PUBLIC_SANITY_PROJECT_ID=$NEXT_PUBLIC_SANITY_PROJECT_ID
ENV NEXT_PUBLIC_SITE_ENV=$NEXT_PUBLIC_SITE_ENV
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_STUDIO_URL=$NEXT_PUBLIC_STUDIO_URL
ENV NEXT_RESEND_FROM_EMAIL=$NEXT_RESEND_FROM_EMAIL
ENV NEXT_RESEND_TO_EMAIL=$NEXT_RESEND_TO_EMAIL
ENV NX_DAEMON=$NX_DAEMON
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV REVALIDATE_SECRET=$REVALIDATE_SECRET
ENV SANITY_API_READ_TOKEN=$SANITY_API_READ_TOKEN
ENV SANITY_AUTH_TOKEN=$SANITY_AUTH_TOKEN
ENV SANITY_DEPLOY=$SANITY_DEPLOY
ENV SANITY_DEV=$SANITY_DEV
ENV SANITY_STUDIO_API_VERSION=$SANITY_STUDIO_API_VERSION
ENV SANITY_STUDIO_APP_ID=$SANITY_STUDIO_APP_ID
ENV SANITY_STUDIO_DATASET=$SANITY_STUDIO_DATASET
ENV SANITY_STUDIO_HOSTNAME=$SANITY_STUDIO_HOSTNAME
ENV SANITY_STUDIO_PREVIEW_URL=$SANITY_STUDIO_PREVIEW_URL
ENV SANITY_STUDIO_PROJECT_ID=$SANITY_STUDIO_PROJECT_ID
ENV SEO_DASHBOARD_PASSWORD=$SEO_DASHBOARD_PASSWORD
ENV SEO_SESSION_SECRET=$SEO_SESSION_SECRET
ENV SEO_SETTINGS_ENCRYPTION_KEY=$SEO_SETTINGS_ENCRYPTION_KEY
ENV TURBO_CACHE=$TURBO_CACHE
ENV TURBO_DOWNLOAD_LOCAL_ENABLED=$TURBO_DOWNLOAD_LOCAL_ENABLED
ENV TURBO_REMOTE_ONLY=$TURBO_REMOTE_ONLY
ENV TURBO_RUN_SUMMARY=$TURBO_RUN_SUMMARY

# Copy monorepo manifests
COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml ./
COPY frontend/package.json ./frontend/

# Install all dependencies (needed so build + pnpm deploy can resolve)
RUN pnpm install --no-frozen-lockfile

# Copy sources
COPY . .

# Build the frontend (webpack mode, high memory)
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN pnpm --filter frontend run build

# Produce a self-contained production deployment of the frontend workspace
RUN pnpm --filter frontend deploy --legacy /app/prod
# .next is gitignored, so pnpm deploy skips it — copy it explicitly
RUN cp -r /app/frontend/.next /app/prod/.next

# ---- Runner ----
FROM node:22-alpine AS runner
WORKDIR /app/prod
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

COPY --from=builder /app/prod ./

EXPOSE 3000
CMD ["node_modules/.bin/next", "start"]
