import { Image as ImageIcon } from "lucide-react";
import { defineField, defineType } from "sanity";

export default defineType({
  name: "ogSettings",
  title: "OG Settings",
  type: "document",
  icon: ImageIcon,
  fieldsets: [
    { name: "corners", title: "Corner Texts", options: { columns: 2 } },
    { name: "colors", title: "Colors", options: { columns: 2 } },
    { name: "typography", title: "Typography", options: { columns: 3 } },
    { name: "icon", title: "Icon", options: { columns: 2 } },
    { name: "spacing", title: "Spacing & Sizing", options: { columns: 3 } },
  ],
  initialValue: {
    eyebrow: "KotaCom",
    defaultBadge: "Blog",
    headerRightText: "",
    footerLeftText: "",
    footerRightText: "",
    gradientFrom: { _type: "color", hex: "#0B1220" },
    gradientTo: { _type: "color", hex: "#1E293B" },
    accentColor: { _type: "color", hex: "#22D3EE" },
    textColor: { _type: "color", hex: "#FFFFFF" },
    fontFamily: "Geist",
    titleMaxLength: 140,
    titleFontSize: 82,
    titleLineHeight: 1.08,
    titleLetterSpacingEm: -0.03,
    titleClampLines: 3,
    canvasPaddingX: 76,
    canvasPaddingY: 68,
    headerDotSize: 10,
    badgeBorderWidth: 1,
    badgeBorderRadius: 999,
    footerBorderColor: { _type: "color", hex: "#FFFFFF" },
    footerBorderOpacity: 0.18,
    overlayEnabled: true,
    overlayOpacity: 0.12,
    showTitleIcon: true,
    randomizeTitleIcon: true,
    titleAlign: "left",
    titleCaseMode: "none",
    cornerCaseMode: "none",
    stylePreset: "morphglass",
    subtitleText: "",
    iconSize: 48,
    iconCardSize: 92,
    iconCardRadius: 24,
    iconCardBorderWidth: 1,
    iconCardBgColor: { _type: "color", hex: "#111827" },
    iconCardBorderColor: { _type: "color", hex: "#22D3EE" },
  },
  fields: [
    defineField({
      name: "eyebrow",
      title: "Eyebrow Label",
      type: "string",
      initialValue: "KotaCom",
    fieldset: "corners",
    }),
    defineField({
      name: "showEyebrow",
      title: "Show Eyebrow (Top Left)",
      type: "boolean",
      initialValue: true,
    fieldset: "corners",
    }),
    defineField({
      name: "defaultBadge",
      title: "Default Badge",
      type: "string",
      initialValue: "Insights",
    }),
    defineField({
      name: "headerRightText",
      title: "Header Right Text Override",
      type: "string",
      description: "Optional text override for top-right badge content.",
    fieldset: "corners",
    }),
    defineField({
      name: "showHeaderRight",
      title: "Show Header Right (Top Right)",
      type: "boolean",
      initialValue: true,
    fieldset: "corners",
    }),
    defineField({
      name: "footerLeftText",
      title: "Footer Left Text Override",
      type: "string",
      description: "Optional text override for bottom-left footer content.",
    fieldset: "corners",
    }),
    defineField({
      name: "showFooterLeft",
      title: "Show Footer Left (Bottom Left)",
      type: "boolean",
      initialValue: true,
    fieldset: "corners",
    }),
    defineField({
      name: "footerRightText",
      title: "Footer Right Text Override",
      type: "string",
      description: "Optional text override for bottom-right footer content.",
    fieldset: "corners",
    }),
    defineField({
      name: "showFooterRight",
      title: "Show Footer Right (Bottom Right)",
      type: "boolean",
      initialValue: true,
    fieldset: "corners",
    }),
    defineField({
      name: "gradientFrom",
      title: "Gradient From",
      type: "color",
      description: "Hex color only (alpha disabled). Example: #0B1220",
      options: { disableAlpha: true },
    fieldset: "colors",
    }),
    defineField({
      name: "gradientTo",
      title: "Gradient To",
      type: "color",
      description: "Hex color only (alpha disabled). Example: #1E293B",
      options: { disableAlpha: true },
    fieldset: "colors",
    }),
    defineField({
      name: "accentColor",
      title: "Accent Color",
      type: "color",
      description: "Hex color only (alpha disabled). Used for accents and borders.",
      options: { disableAlpha: true },
    fieldset: "colors",
    }),
    defineField({
      name: "textColor",
      title: "Text Color",
      type: "color",
      description: "Hex color only (alpha disabled). Main text color.",
      options: { disableAlpha: true },
    fieldset: "colors",
    }),
    defineField({
      name: "showTitleIcon",
      title: "Show Icon Above Title",
      type: "boolean",
      initialValue: true,
    fieldset: "icon",
    }),
    defineField({
      name: "randomizeTitleIcon",
      title: "Randomize Icon",
      type: "boolean",
      description: "If enabled, icon changes by title hash. If disabled, selected icon is used.",
      initialValue: true,
    fieldset: "icon",
    }),
    defineField({
      name: "titleIcon",
      title: "Title Icon",
      type: "ui-icon",
      description: "Icon picker source for title icon (used when randomize is disabled).",
      hidden: ({ parent }) => Boolean(parent?.randomizeTitleIcon),
    }),
    defineField({
      name: "titleAlign",
      title: "Title Alignment",
      type: "string",
      initialValue: "left",
      options: {
        list: [
          { title: "Left", value: "left" },
          { title: "Center", value: "center" },
        ],
        layout: "radio",
      },
      validation: (Rule) => Rule.required(),
      description: "Choose text flow. `center` centers title + subtitle block, `left` aligns to left.",
    }),
    defineField({
      name: "titleCaseMode",
      title: "Title Case",
      type: "string",
      initialValue: "none",
      options: {
        list: [
          { title: "Normal", value: "none" },
          { title: "UPPERCASE", value: "uppercase" },
          { title: "lowercase", value: "lowercase" },
        ],
        layout: "radio",
      },
      description: "Text transform for title and subtitle.",
    }),
    defineField({
      name: "cornerCaseMode",
      title: "Corner Text Case",
      type: "string",
      initialValue: "none",
      options: {
        list: [
          { title: "Normal", value: "none" },
          { title: "UPPERCASE", value: "uppercase" },
          { title: "lowercase", value: "lowercase" },
        ],
        layout: "radio",
      },
      description: "Text transform for corner/header/footer labels.",
    }),
    defineField({
      name: "stylePreset",
      title: "Style Preset",
      type: "string",
      initialValue: "morphglass",
      options: {
        list: [
          { title: "Morphglass", value: "morphglass" },
          { title: "Classic", value: "classic" },
        ],
        layout: "radio",
      },
      description: "`Morphglass` adds glass panels and glow. `Classic` keeps flat style.",
    }),
    defineField({
      name: "subtitleText",
      title: "Subtitle Text (Below Title)",
      type: "string",
      description: "Optional line under title. Will render with WhatsApp icon.",
    }),
    defineField({
      name: "iconSize",
      title: "Icon Size",
      type: "number",
      initialValue: 48,
      description: "Range: 20-120 px",
      validation: (Rule) => Rule.min(20).max(120),
    fieldset: "icon",
    }),
    defineField({
      name: "iconCardSize",
      title: "Icon Card Size",
      type: "number",
      initialValue: 92,
      description: "Range: 48-180 px",
      validation: (Rule) => Rule.min(48).max(180),
    fieldset: "icon",
    }),
    defineField({
      name: "iconCardRadius",
      title: "Icon Card Radius",
      type: "number",
      initialValue: 24,
      description: "Range: 0-999 px",
      validation: (Rule) => Rule.min(0).max(999),
    }),
    defineField({
      name: "iconCardBorderWidth",
      title: "Icon Card Border Width",
      type: "number",
      initialValue: 1,
      description: "Range: 0-8 px",
      validation: (Rule) => Rule.min(0).max(8),
    }),
    defineField({
      name: "iconCardBgColor",
      title: "Icon Card Background",
      type: "color",
      description: "Hex color only (alpha disabled).",
      options: { disableAlpha: true },
    }),
    defineField({
      name: "iconCardBorderColor",
      title: "Icon Card Border Color",
      type: "color",
      description: "Hex color only (alpha disabled).",
      options: { disableAlpha: true },
    }),
    defineField({
      name: "fontFamily",
      title: "Font Family Name",
      type: "string",
      description: "Used as CSS font-family label for OG canvas.",
      initialValue: "Inter",
    }),
    defineField({
      name: "fontUrl",
      title: "Font URL (TTF/OTF/WOFF)",
      type: "url",
      description:
        "Optional remote font URL for custom typography. If empty/unreachable, system uses built-in Geist fallback.",
      validation: (Rule) =>
        Rule.uri({
          scheme: ["http", "https"],
        }),
    }),
    defineField({
      name: "titleMaxLength",
      title: "Title Max Length",
      type: "number",
      initialValue: 140,
      description: "Range: 40-220 characters",
      validation: (Rule) => Rule.min(40).max(220),
    }),
    defineField({
      name: "titleFontSize",
      title: "Title Font Size",
      type: "number",
      initialValue: 82,
      description: "Range: 32-120 px",
      validation: (Rule) => Rule.min(32).max(120),
    fieldset: "typography",
    }),
    defineField({
      name: "titleLineHeight",
      title: "Title Line Height",
      type: "number",
      initialValue: 1.08,
      description: "Range: 0.9-1.6",
      validation: (Rule) => Rule.min(0.9).max(1.6),
    fieldset: "typography",
    }),
    defineField({
      name: "titleLetterSpacingEm",
      title: "Title Letter Spacing (em)",
      type: "number",
      initialValue: -0.03,
      description: "Range: -0.2 to 0.2 em",
      validation: (Rule) => Rule.min(-0.2).max(0.2),
    fieldset: "typography",
    }),
    defineField({
      name: "titleClampLines",
      title: "Title Clamp Lines",
      type: "number",
      initialValue: 3,
      description: "Range: 1-5 lines",
      validation: (Rule) => Rule.min(1).max(5),
    fieldset: "typography",
    }),
    defineField({
      name: "canvasPaddingX",
      title: "Canvas Padding X",
      type: "number",
      initialValue: 76,
      description: "Range: 24-180 px",
      validation: (Rule) => Rule.min(24).max(180),
    fieldset: "spacing",
    }),
    defineField({
      name: "canvasPaddingY",
      title: "Canvas Padding Y",
      type: "number",
      initialValue: 68,
      description: "Range: 24-180 px",
      validation: (Rule) => Rule.min(24).max(180),
    fieldset: "spacing",
    }),
    defineField({
      name: "headerDotSize",
      title: "Header Dot Size",
      type: "number",
      initialValue: 10,
      description: "Range: 4-24 px",
      validation: (Rule) => Rule.min(4).max(24),
    fieldset: "spacing",
    }),
    defineField({
      name: "badgeBorderWidth",
      title: "Badge Border Width",
      type: "number",
      initialValue: 1,
      description: "Range: 0-8 px",
      validation: (Rule) => Rule.min(0).max(8),
    }),
    defineField({
      name: "badgeBorderRadius",
      title: "Badge Border Radius",
      type: "number",
      initialValue: 999,
      description: "Range: 0-999 px",
      validation: (Rule) => Rule.min(0).max(999),
    }),
    defineField({
      name: "footerBorderColor",
      title: "Footer Border Color",
      type: "color",
      description: "Hex color only (alpha disabled).",
      options: { disableAlpha: true },
    }),
    defineField({
      name: "footerBorderOpacity",
      title: "Footer Border Opacity",
      type: "number",
      initialValue: 0.18,
      description: "Range: 0-1",
      validation: (Rule) => Rule.min(0).max(1),
    }),
    defineField({
      name: "overlayEnabled",
      title: "Enable Accent Overlay",
      type: "boolean",
      initialValue: true,
    }),
    defineField({
      name: "overlayOpacity",
      title: "Overlay Opacity",
      type: "number",
      initialValue: 0.12,
      description: "Range: 0-1",
      validation: (Rule) => Rule.min(0).max(1),
    }),
  ],
  preview: {
    select: {
      title: "eyebrow",
    },
    prepare({ title }) {
      return {
        title: title || "OG Settings",
        subtitle: "Global Open Graph image visual configuration",
      };
    },
  },
});
