/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Price = {
  value?: number;
  period?: string;
};

export type Meta = {
  title?: string;
  description?: string;
  canonicalUrl?: string;
  focusKeyword?: string;
  secondaryKeywords?: Array<string>;
  noindex?: boolean;
  image?: MetaImage;
  ogGeneratedAt?: string;
  ogGenerationSource?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type MetaImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "meta.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type StatsHeroBlock = {
  _type: "stats-hero-block";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  eyebrow?: string;
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  links?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type ValuePropsBlock = {
  _type: "value-props-block";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  title?: string;
  description?: string;
  valueProps?: Array<{
    icon?: string;
    title?: string;
    description?: string;
    _type: "valueProp";
    _key: string;
  }>;
};

export type ProblemSolutionBlock = {
  _type: "problem-solution-block";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  title?: string;
  problems?: Array<string>;
  solutionTitle?: string;
  solution?: string;
};

export type ServiceTypesBlock = {
  _type: "service-types-block";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  title?: string;
  description?: string;
  services?: Array<{
    title?: string;
    description?: string;
    features?: Array<string>;
    price?: string;
    timeline?: string;
    badge?: string;
    link?: Link;
    _type: "serviceType";
    _key: string;
  }>;
};

export type FeaturesPackageBlock = {
  _type: "features-package-block";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  title?: string;
  subtitle?: string;
  description?: string;
  features?: Array<{
    icon?: string;
    title?: string;
    description?: string;
    badge?: string;
    _type: "feature";
    _key: string;
  }>;
};

export type BenefitsBlock = {
  _type: "benefits-block";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  title?: string;
  subtitle?: string;
  description?: string;
  benefits?: Array<{
    icon?: string;
    title?: string;
    description?: string;
    badge?: string;
    badgeIcon?: string;
    _type: "benefit";
    _key: string;
  }>;
};

export type PricingBlock = {
  _type: "pricing-block";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  title?: string;
  description?: string;
  category?: "website" | "software" | "printing";
};

export type TestimonialsBlock = {
  _type: "testimonials-block";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  title?: string;
  description?: string;
  category?: "" | "website" | "software" | "printing";
};

export type FaqBlock = {
  _type: "faq-block";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  title?: string;
  description?: string;
  category?: "website" | "software" | "printing";
};

export type CompanyInfo = {
  _type: "company-info";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  title?: string;
  description?: string;
};

export type LegacyRichContent = {
  _type: "legacy-rich-content";
  title?: string;
  excerpt?: string;
  contentFormat?: "markdown" | "html";
  contentRaw?: string;
};

export type AllPosts = {
  _type: "all-posts";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  displayMode?: "default" | "carousel";
  contentTypes?: Array<string>;
  limit?: number;
};

export type FormNewsletter = {
  _type: "form-newsletter";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  stackAlign?: "left" | "center";
  consentText?: string;
  buttonText?: string;
  successMessage?: string;
};

export type FaqReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faq";
};

export type Faqs = {
  _type: "faqs";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
};

export type LogoCloud1 = {
  _type: "logo-cloud-1";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  title?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type WhatsappCta = {
  _type: "whatsapp-cta";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  sectionWidth?: "default" | "narrow";
  stackAlign?: "left" | "center";
  tagLine?: string;
  uiIcon?: UiIcon;
  title?: string;
  body?: BlockContent;
  secondaryLink?: Link;
};

export type Cta1 = {
  _type: "cta-1";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  sectionWidth?: "default" | "narrow";
  stackAlign?: "left" | "center";
  tagLine?: string;
  uiIcon?: UiIcon;
  title?: string;
  body?: BlockContent;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Timelines1 = {
  _type: "timelines-1";
  title?: string;
  tagLine?: string;
  body?: BlockContent;
};

export type TimelineRow = {
  _type: "timeline-row";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  timelines?: Array<
    {
      _key: string;
    } & Timelines1
  >;
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type Carousel2 = {
  _type: "carousel-2";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  testimonial?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
};

export type Carousel1 = {
  _type: "carousel-1";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  size?: "one" | "two" | "three";
  indicators?: "none" | "dots" | "count";
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type GridRow = {
  _type: "grid-row";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  textAlign?: "left" | "center";
  cardLayout?: "vertical" | "horizontal";
  gridColumns?: "grid-cols-2" | "grid-cols-3" | "grid-cols-4";
  columns?: Array<
    | ({
        _key: string;
      } & GridCard)
    | ({
        _key: string;
      } & GridPost)
    | ({
        _key: string;
      } & PricingCard)
  >;
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type GridPost = {
  _type: "grid-post";
  post?: PostReference;
};

export type PricingCard = {
  _type: "pricing-card";
  uiIcon?: UiIcon;
  title?: string;
  tagLine?: string;
  price?: Price;
  list?: Array<string>;
  excerpt?: string;
  link?: Link;
};

export type GridCard = {
  _type: "grid-card";
  uiIcon?: UiIcon;
  cardStyle?: "vercel" | "classic";
  title?: string;
  excerpt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  link?: Link;
};

export type SplitInfo = {
  _type: "split-info";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  uiIcon?: UiIcon;
  title?: string;
  body?: BlockContent;
  tags?: Array<string>;
};

export type SplitInfoList = {
  _type: "split-info-list";
  list?: Array<
    {
      _key: string;
    } & SplitInfo
  >;
};

export type SplitImage = {
  _type: "split-image";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SplitCard = {
  _type: "split-card";
  tagLine?: string;
  uiIcon?: UiIcon;
  title?: string;
  body?: BlockContent;
};

export type SplitCardsList = {
  _type: "split-cards-list";
  list?: Array<
    {
      _key: string;
    } & SplitCard
  >;
};

export type SplitContent = {
  _type: "split-content";
  sticky?: boolean;
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  tagLine?: string;
  title?: string;
  body?: BlockContent;
  link?: Link;
};

export type SplitRow = {
  _type: "split-row";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  noGap?: boolean;
  splitColumns?: Array<
    | ({
        _key: string;
      } & SplitContent)
    | ({
        _key: string;
      } & SplitCardsList)
    | ({
        _key: string;
      } & SplitImage)
    | ({
        _key: string;
      } & SplitInfoList)
  >;
};

export type SectionHeader = {
  _type: "section-header";
  padding?: SectionPadding;
  colorVariant?: ColorVariant;
  sectionWidth?: "default" | "narrow";
  stackAlign?: "left" | "center";
  tagLine?: string;
  title?: string;
  description?: string;
};

export type HeroFeatureCard = {
  _type: "hero-feature-card";
  uiIcon?: UiIcon;
  title?: string;
  description?: string;
};

export type HeroVercel = {
  _type: "hero-vercel";
  tagLine?: string;
  title?: string;
  description?: string;
  ctaPrimary?: Link;
  ctaSecondary?: Link;
  cards?: Array<
    {
      _key: string;
    } & HeroFeatureCard
  >;
};

export type Hero2 = {
  _type: "hero-2";
  tagLine?: string;
  uiIcon?: UiIcon;
  title?: string;
  body?: BlockContent;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  links?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Hero1 = {
  _type: "hero-1";
  tagLine?: string;
  uiIcon?: UiIcon;
  title?: string;
  body?: BlockContent;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  links?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type GeneratorProgramReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "generatorProgram";
};

export type GeneratorTemplateReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "generatorTemplate";
};

export type GeneratorDatasetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "generatorDataset";
};

export type GeneratorPageMeta = {
  _type: "generatorPageMeta";
  programId?: string;
  program?: GeneratorProgramReference;
  templateId?: string;
  template?: GeneratorTemplateReference;
  datasetId?: string;
  dataset?: GeneratorDatasetReference;
  rowKey?: string;
  keywordKey?: string;
  generatedAt?: string;
  version?: string;
  aiUsed?: boolean;
};

export type GeneratorRow = {
  _type: "generatorRow";
  key?: string;
  label?: string;
  service?: string;
  city?: string;
  industry?: string;
  offer?: string;
};

export type GeneratorKeywordSet = {
  _type: "generatorKeywordSet";
  key?: string;
  label?: string;
  primaryKeyword?: string;
  secondaryKeywords?: Array<string>;
  angle?: string;
};

export type GeneratorTokenDefinition = {
  _type: "generatorTokenDefinition";
  name?: string;
  label?: string;
  sourceField?: string;
  fallbackValue?: string;
  required?: boolean;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: string;
};

export type PricingPackage = {
  _type: "pricingPackage";
  name?: string;
  price?: number;
  currency?: string;
  priceUnit?: string;
  duration?: string;
  features?: Array<string>;
  excluded?: Array<string>;
  paymentTerms?: string;
  bestFor?: string;
};

export type TemplateSourcePolicy = {
  _type: "templateSourcePolicy";
  pricingSource?:
    | "page-first"
    | "template-first"
    | "template-only"
    | "page-only"
    | "base-only";
  proofSource?:
    | "page-first"
    | "template-first"
    | "template-only"
    | "page-only"
    | "base-only";
  testimonialSource?:
    | "page-first"
    | "template-first"
    | "template-only"
    | "page-only"
    | "base-only";
  maxQuickLinks?: number;
};

export type TemplateRewriteCopy = {
  _type: "templateRewriteCopy";
  heroBadge?: string;
  primaryKeyword?: string;
  subheadline?: string;
  secondaryKeywords?: Array<string>;
  description?: string;
  intro?: string;
  valueProposition?: string;
  problemStatement?: string;
  guarantee?: string;
  stats?: Array<{
    value?: string;
    label?: string;
    _key: string;
  }>;
  highlights?: Array<string>;
  eeatPoints?: Array<
    {
      _key: string;
    } & TemplateEeatPoint
  >;
  process?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & TemplateFaq
  >;
  ctaLabel?: string;
  ctaLink?: Link;
  ctaLinks?: Array<
    {
      _key: string;
    } & TemplateCtaLink
  >;
  serviceTypes?: Array<
    {
      _key: string;
    } & TemplateServiceType
  >;
  pricingPlans?: Array<
    {
      _key: string;
    } & TemplatePricingPlan
  >;
  features?: Array<
    {
      _key: string;
    } & TemplateFeature
  >;
  proofItems?: Array<
    {
      _key: string;
    } & TemplateProofItem
  >;
  testimonials?: Array<
    {
      _key: string;
    } & TemplateTestimonial
  >;
  longGuide?: Array<
    {
      _key: string;
    } & TemplateLongGuide
  >;
  finalCtaTitle?: string;
  finalCtaDescription?: string;
  contentVariants?: Array<
    {
      _key: string;
    } & TemplateContentVariant
  >;
};

export type TemplateContentVariant = {
  _type: "templateContentVariant";
  slot?:
    | "heroEyebrow"
    | "primaryKeyword"
    | "intro"
    | "description"
    | "ctaLabel"
    | "finalCtaTitle"
    | "finalCtaDescription";
  text?: string;
  lane?: "website" | "software" | "printing" | "generic";
  intent?: "awareness" | "commercial" | "decision";
  strength?: "safe" | "aggressive";
  requiresLocation?: boolean;
  requiresService?: boolean;
  routeKinds?: Array<string>;
  disallowedContexts?: Array<string>;
};

export type TemplateLongGuide = {
  _type: "templateLongGuide";
  title?: string;
  description?: string;
};

export type TemplateTestimonial = {
  _type: "templateTestimonial";
  name?: string;
  role?: string;
  company?: string;
  industry?: string;
  quote?: string;
  result?: string;
  rating?: number;
  verified?: boolean;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type TemplateProofItem = {
  _type: "templateProofItem";
  stat?: string;
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  link?: Link;
};

export type TemplateEeatPoint = {
  _type: "templateEeatPoint";
  title?: string;
  description?: string;
};

export type TemplateFeature = {
  _type: "templateFeature";
  title?: string;
  description?: string;
  icon?:
    | "speed"
    | "security"
    | "conversion"
    | "design"
    | "support"
    | "ecommerce"
    | "boxes"
    | "analytics"
    | "integration"
    | "pricing"
    | "mobile"
    | "custom";
  badge?: string;
};

export type TemplatePricingPlan = {
  _type: "templatePricingPlan";
  name?: string;
  badge?: string;
  price?: string;
  description?: string;
  items?: Array<string>;
  excludes?: Array<string>;
  timeline?: string;
  paymentTerms?: string;
  recommended?: boolean;
  ctaLink?: Link;
};

export type TemplateServiceType = {
  _type: "templateServiceType";
  title?: string;
  targetAudience?: string;
  description?: string;
  features?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  link?: Link;
};

export type TemplateFaq = {
  _type: "templateFaq";
  question?: string;
  answer?: string;
};

export type TemplateCtaLink = {
  _type: "templateCtaLink";
  label?: string;
  link?: Link;
};

export type AffiliateItem = {
  _type: "affiliateItem";
  itemType?: "product" | "software" | "service" | "webapp" | "mobileapp";
  name?: string;
  brand?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  description?: string;
  pros?: Array<string>;
  cons?: Array<string>;
  rating?: number;
  price?: number;
  currency?: "IDR" | "USD" | "EUR";
  affiliateUrl?: string;
  affiliateLabel?: string;
  availability?:
    | "in-stock"
    | "out-of-stock"
    | "pre-order"
    | "free"
    | "freemium";
  sku?: string;
  position?: number;
  verdict?: string;
};

export type AggregateRating = {
  _type: "aggregateRating";
  ratingValue?: number;
  reviewCount?: number;
  bestRating?: number;
  ratingSource?:
    | "google-maps"
    | "internal"
    | "tokopedia"
    | "shopee"
    | "calculated"
    | "other";
  sourceUrl?: string;
};

export type ReviewItem = {
  _type: "reviewItem";
  reviewerName?: string;
  reviewerRole?: string;
  reviewerImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  rating?: number;
  reviewBody?: string;
  datePublished?: string;
  source?: "google-maps" | "tokopedia" | "shopee" | "internal" | "other";
  sourceUrl?: string;
  verified?: boolean;
};

export type SectionPadding = {
  _type: "section-padding";
  top?: boolean;
  bottom?: boolean;
};

export type UiIcon = IconPicker;

export type NavigationIcon =
  | "home"
  | "grid"
  | "product"
  | "service"
  | "blog"
  | "docs"
  | "page"
  | "company"
  | "contact"
  | "pricing"
  | "growth"
  | "rocket"
  | "ai"
  | "magic"
  | "workflow"
  | "security"
  | "search"
  | "support"
  | "help"
  | "global"
  | "labs"
  | "program";

export type ButtonVariant =
  | "default"
  | "destructive"
  | "outline"
  | "secondary"
  | "ghost"
  | "link";

export type ColorVariant =
  | "background"
  | "primary"
  | "secondary"
  | "card"
  | "accent"
  | "destructive"
  | "muted";

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type NavigationLinkChild = {
  _type: "navigation-link-child";
  isExternal?: boolean;
  internalLink?:
    | PageReference
    | PostReference
    | CategoryReference
    | ProductReference
    | ServiceReference
    | ProjectReference;
  title?: string;
  description?: string;
  badge?: string;
  group?: string;
  icon?: NavigationIcon;
  uiIcon?: UiIcon;
  href?: string;
  target?: boolean;
};

export type Link = {
  _type: "link";
  isExternal?: boolean;
  internalLink?:
    | PageReference
    | PostReference
    | CategoryReference
    | ProductReference
    | ServiceReference
    | ProjectReference;
  title?: string;
  href?: string;
  target?: boolean;
  buttonVariant?: ButtonVariant;
  navLocation?: "primary" | "more" | "utility";
  showInFooter?: boolean;
  showInHeader?: boolean;
  icon?: NavigationIcon;
  uiIcon?: UiIcon;
  children?: Array<
    {
      _key: string;
    } & NavigationLinkChild
  >;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        isExternal?: boolean;
        internalLink?:
          | PageReference
          | PostReference
          | ServiceReference
          | ProductReference
          | ProjectReference;
        href?: string;
        target?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
  | {
      videoId?: string;
      _type: "youtube";
      _key: string;
    }
  | ({
      _key: string;
    } & Code)
  | ({
      _key: string;
    } & LegacyRichContent)
>;

export type ServiceCluster = {
  _id: string;
  _type: "serviceCluster";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  href?: string;
  priceHint?: string;
  bullets?: Array<string>;
  order?: number;
  isActive?: "active" | "inactive";
};

export type ServiceLane = {
  _id: string;
  _type: "serviceLane";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  key?: "website" | "software" | "support" | "printing";
  eyebrow?: string;
  title?: string;
  description?: string;
  href?: string;
  bullets?: Array<string>;
  order?: number;
  isActive?: "active" | "inactive";
};

export type WhyChooseReason = {
  _id: string;
  _type: "whyChooseReason";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  icon?:
    | "award"
    | "heart-handshake"
    | "shield"
    | "trending-up"
    | "check-circle"
    | "star"
    | "zap"
    | "users";
  order?: number;
  isActive?: "active" | "inactive";
};

export type HomeContent = {
  _id: string;
  _type: "homeContent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroTitle?: string;
  heroDescription?: string;
  heroPrimaryCta?: {
    label?: string;
    href?: string;
  };
  heroSecondaryCta?: {
    label?: string;
    href?: string;
  };
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  foundedYear?: number;
  projectsCompleted?: number;
  location?: string;
  coverage?: string;
  servicesEyebrow?: string;
  servicesTitle?: string;
  servicesDescription?: string;
  workflowTitle?: string;
  workflowSteps?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
  closingTitle?: string;
  closingDescription?: string;
  assurancePoints?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  keywords?: Array<string>;
  companyName?: string;
  companyTagline?: string;
  companyDescription?: string;
  foundedYear?: number;
  projectsCompleted?: number;
  location?: string;
  coverage?: string;
  phone?: string;
  whatsapp?: string;
  email?: string;
  address?: string;
  socialMedia?: {
    facebook?: string;
    instagram?: string;
    linkedin?: string;
    twitter?: string;
    youtube?: string;
  };
  techStack?: Array<string>;
};

export type GeneratorProgram = {
  _id: string;
  _type: "generatorProgram";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  orderRank?: string;
  template?: GeneratorTemplateReference;
  dataset?: GeneratorDatasetReference;
  programType?: "landing-pages" | "location-pages";
  generationMode?: "preview" | "batch";
  routeBase?: string;
  slugTokenReference?: string;
  slugPattern?: string;
  defaultSeoPattern?: {
    title?: string;
    description?: string;
  };
  status?: "draft" | "ready" | "paused";
  aiMode?: "off" | "prepared";
  devOnly?: boolean;
};

export type GeneratorDataset = {
  _id: string;
  _type: "generatorDataset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  orderRank?: string;
  keywordSets?: Array<
    {
      _key: string;
    } & GeneratorKeywordSet
  >;
  rows?: Array<
    {
      _key: string;
    } & GeneratorRow
  >;
  importMode?: "manual" | "csv-ready";
  keywordSetCsv?: string;
  rowCsv?: string;
  dedupePolicy?: "skip-existing-slug" | "flag-conflict";
  status?: "draft" | "ready" | "archived";
  devOnly?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type GeneratorTemplate = {
  _id: string;
  _type: "generatorTemplate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  orderRank?: string;
  description?: string;
  visualPreset?:
    | "editorial-grid"
    | "proof-showcase"
    | "pricing-spotlight"
    | "conversion-stack"
    | "immersive-story"
    | "trust-matrix"
    | "authority-canvas"
    | "offer-funnel"
    | "process-mosaic";
  motionPreset?:
    | "calm-reveal"
    | "stagger-rise"
    | "spotlight-flow"
    | "crisp-snap";
  styleNotes?: string;
  outputType?: "page";
  blockTokenReference?: string;
  blocks?: Array<
    | ({
        _key: string;
      } & Hero1)
    | ({
        _key: string;
      } & Hero2)
    | ({
        _key: string;
      } & StatsHeroBlock)
    | ({
        _key: string;
      } & SectionHeader)
    | ({
        _key: string;
      } & SplitRow)
    | ({
        _key: string;
      } & GridRow)
    | ({
        _key: string;
      } & Carousel1)
    | ({
        _key: string;
      } & Carousel2)
    | ({
        _key: string;
      } & TimelineRow)
    | ({
        _key: string;
      } & Cta1)
    | ({
        _key: string;
      } & WhatsappCta)
    | ({
        _key: string;
      } & LogoCloud1)
    | ({
        _key: string;
      } & Faqs)
    | ({
        _key: string;
      } & FormNewsletter)
    | ({
        _key: string;
      } & AllPosts)
    | ({
        _key: string;
      } & LegacyRichContent)
    | ({
        _key: string;
      } & CompanyInfo)
    | ({
        _key: string;
      } & TestimonialsBlock)
    | ({
        _key: string;
      } & PricingBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & BenefitsBlock)
    | ({
        _key: string;
      } & FeaturesPackageBlock)
    | ({
        _key: string;
      } & ServiceTypesBlock)
    | ({
        _key: string;
      } & ProblemSolutionBlock)
    | ({
        _key: string;
      } & ValuePropsBlock)
  >;
  designFamily?: string;
  status?: "draft" | "ready" | "paused";
  tokenDefinitions?: Array<
    {
      _key: string;
    } & GeneratorTokenDefinition
  >;
  devOnly?: boolean;
};

export type LegacyPage = {
  _id: string;
  _type: "legacyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  route?: string;
  templateVariant?: "default" | "narrative" | "case-study" | "faq-heavy";
  heroOverride?: {
    title?: string;
    subtitle?: string;
    eyebrow?: string;
    ctaLabel?: string;
    ctaHref?: string;
    secondaryKeywords?: Array<string>;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  highlightsOverride?: Array<string>;
  faqOverride?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
  sectionOrder?: Array<string>;
  customBlocks?: Array<
    | ({
        _key: string;
      } & Hero1)
    | ({
        _key: string;
      } & Hero2)
    | ({
        _key: string;
      } & SectionHeader)
    | ({
        _key: string;
      } & SplitRow)
    | ({
        _key: string;
      } & GridRow)
    | ({
        _key: string;
      } & Carousel1)
    | ({
        _key: string;
      } & Carousel2)
    | ({
        _key: string;
      } & TimelineRow)
    | ({
        _key: string;
      } & Cta1)
    | ({
        _key: string;
      } & WhatsappCta)
    | ({
        _key: string;
      } & LogoCloud1)
    | ({
        _key: string;
      } & Faqs)
    | ({
        _key: string;
      } & FormNewsletter)
    | ({
        _key: string;
      } & AllPosts)
    | ({
        _key: string;
      } & LegacyRichContent)
  >;
  meta?: Meta;
};

export type ReusableSection = {
  _id: string;
  _type: "reusableSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  isActive?: boolean;
  priority?: number;
  placements?: Array<string>;
  routeMode?: "all" | "selected";
  routeSlugs?: Array<string>;
  blocks?: Array<
    | ({
        _key: string;
      } & Hero1)
    | ({
        _key: string;
      } & Hero2)
    | ({
        _key: string;
      } & StatsHeroBlock)
    | ({
        _key: string;
      } & SectionHeader)
    | ({
        _key: string;
      } & SplitRow)
    | ({
        _key: string;
      } & GridRow)
    | ({
        _key: string;
      } & Carousel1)
    | ({
        _key: string;
      } & Carousel2)
    | ({
        _key: string;
      } & TimelineRow)
    | ({
        _key: string;
      } & Cta1)
    | ({
        _key: string;
      } & WhatsappCta)
    | ({
        _key: string;
      } & LogoCloud1)
    | ({
        _key: string;
      } & Faqs)
    | ({
        _key: string;
      } & FormNewsletter)
    | ({
        _key: string;
      } & AllPosts)
    | ({
        _key: string;
      } & LegacyRichContent)
    | ({
        _key: string;
      } & CompanyInfo)
    | ({
        _key: string;
      } & TestimonialsBlock)
    | ({
        _key: string;
      } & PricingBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & BenefitsBlock)
    | ({
        _key: string;
      } & FeaturesPackageBlock)
    | ({
        _key: string;
      } & ServiceTypesBlock)
    | ({
        _key: string;
      } & ProblemSolutionBlock)
    | ({
        _key: string;
      } & ValuePropsBlock)
  >;
  orderRank?: string;
};

export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source?: string;
  destination?: string;
  permanent?: boolean;
  isEnabled?: boolean;
};

export type SeoOpsSettings = {
  _id: string;
  _type: "seoOpsSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  googleEnabled?: boolean;
  googleAggressiveMode?: boolean;
  googleServiceAccountEncrypted?: string;
  indexNowEnabled?: boolean;
  indexNowHost?: string;
  indexNowEndpoint?: string;
  indexNowKeyEncrypted?: string;
  indexNowKeyLocation?: string;
  autoSubmitOnRevalidate?: boolean;
  maxBatchSize?: number;
  retryAttempts?: number;
  dashboardPasswordHash?: string;
  notes?: string;
};

export type ServiceTypeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "serviceType";
};

export type LocationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "location";
};

export type PageTemplateReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "pageTemplate";
};

export type ServiceLocation = {
  _id: string;
  _type: "serviceLocation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  route?: string;
  routePattern?: string;
  slug?: Slug;
  service?: ServiceReference;
  serviceType?: ServiceTypeReference;
  location?: LocationReference;
  template?: PageTemplateReference;
  heroEyebrow?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  structured?: TemplateRewriteCopy;
  blocks?: Array<
    | ({
        _key: string;
      } & Hero1)
    | ({
        _key: string;
      } & Hero2)
    | ({
        _key: string;
      } & HeroVercel)
    | ({
        _key: string;
      } & StatsHeroBlock)
    | ({
        _key: string;
      } & SectionHeader)
    | ({
        _key: string;
      } & SplitRow)
    | ({
        _key: string;
      } & GridRow)
    | ({
        _key: string;
      } & Carousel1)
    | ({
        _key: string;
      } & Carousel2)
    | ({
        _key: string;
      } & TimelineRow)
    | ({
        _key: string;
      } & Cta1)
    | ({
        _key: string;
      } & WhatsappCta)
    | ({
        _key: string;
      } & LogoCloud1)
    | ({
        _key: string;
      } & Faqs)
    | ({
        _key: string;
      } & FormNewsletter)
    | ({
        _key: string;
      } & AllPosts)
    | ({
        _key: string;
      } & LegacyRichContent)
    | ({
        _key: string;
      } & CompanyInfo)
    | ({
        _key: string;
      } & TestimonialsBlock)
    | ({
        _key: string;
      } & PricingBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & BenefitsBlock)
    | ({
        _key: string;
      } & FeaturesPackageBlock)
    | ({
        _key: string;
      } & ServiceTypesBlock)
    | ({
        _key: string;
      } & ProblemSolutionBlock)
    | ({
        _key: string;
      } & ValuePropsBlock)
  >;
  topBlockCount?: number;
  contentStatus?: "draft" | "reviewed" | "index";
  meta?: Meta;
};

export type PageLocation = {
  _id: string;
  _type: "pageLocation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  route?: string;
  routePattern?: string;
  slug?: Slug;
  location?: LocationReference;
  template?: PageTemplateReference;
  heroEyebrow?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  structured?: TemplateRewriteCopy;
  blocks?: Array<
    | ({
        _key: string;
      } & Hero1)
    | ({
        _key: string;
      } & Hero2)
    | ({
        _key: string;
      } & HeroVercel)
    | ({
        _key: string;
      } & StatsHeroBlock)
    | ({
        _key: string;
      } & SectionHeader)
    | ({
        _key: string;
      } & SplitRow)
    | ({
        _key: string;
      } & GridRow)
    | ({
        _key: string;
      } & Carousel1)
    | ({
        _key: string;
      } & Carousel2)
    | ({
        _key: string;
      } & TimelineRow)
    | ({
        _key: string;
      } & Cta1)
    | ({
        _key: string;
      } & WhatsappCta)
    | ({
        _key: string;
      } & LogoCloud1)
    | ({
        _key: string;
      } & Faqs)
    | ({
        _key: string;
      } & FormNewsletter)
    | ({
        _key: string;
      } & AllPosts)
    | ({
        _key: string;
      } & LegacyRichContent)
    | ({
        _key: string;
      } & CompanyInfo)
    | ({
        _key: string;
      } & TestimonialsBlock)
    | ({
        _key: string;
      } & PricingBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & BenefitsBlock)
    | ({
        _key: string;
      } & FeaturesPackageBlock)
    | ({
        _key: string;
      } & ServiceTypesBlock)
    | ({
        _key: string;
      } & ProblemSolutionBlock)
    | ({
        _key: string;
      } & ValuePropsBlock)
  >;
  topBlockCount?: number;
  contentStatus?: "draft" | "reviewed" | "index";
  meta?: Meta;
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  province?: string;
  region?: string;
  lat?: number;
  lng?: number;
  highlights?: Array<string>;
  overview?: string;
};

export type OgSettings = {
  _id: string;
  _type: "ogSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  defaultBadge?: string;
  headerRightText?: string;
  footerLeftText?: string;
  footerRightText?: string;
  gradientFrom?: Color;
  gradientTo?: Color;
  accentColor?: Color;
  textColor?: Color;
  showTitleIcon?: boolean;
  randomizeTitleIcon?: boolean;
  titleIcon?: UiIcon;
  titleAlign?: "left" | "center";
  titleCaseMode?: "none" | "uppercase" | "lowercase";
  cornerCaseMode?: "none" | "uppercase" | "lowercase";
  stylePreset?: "morphglass" | "classic";
  subtitleText?: string;
  iconSize?: number;
  iconCardSize?: number;
  iconCardRadius?: number;
  iconCardBorderWidth?: number;
  iconCardBgColor?: Color;
  iconCardBorderColor?: Color;
  fontFamily?: string;
  fontUrl?: string;
  titleMaxLength?: number;
  titleFontSize?: number;
  titleLineHeight?: number;
  titleLetterSpacingEm?: number;
  titleClampLines?: number;
  canvasPaddingX?: number;
  canvasPaddingY?: number;
  headerDotSize?: number;
  badgeBorderWidth?: number;
  badgeBorderRadius?: number;
  footerBorderColor?: Color;
  footerBorderOpacity?: number;
  overlayEnabled?: boolean;
  overlayOpacity?: number;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type SeoSettings = {
  _id: string;
  _type: "seoSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titleSuffix?: string;
  defaultTitle?: string;
  defaultDescription?: string;
  defaultNoIndex?: boolean;
  siteUrl?: string;
  siteSearchPath?: string;
  noIndexBlogCategories?: boolean;
  noIndexProductCategories?: boolean;
  noIndexServiceCategories?: boolean;
  robotsDisallowPaths?: Array<string>;
  aiCrawlerAllowlist?: Array<string>;
  sitemapStaticRoutes?: Array<string>;
  includeTemplateRoutesInSitemap?: boolean;
  twitterHandle?: string;
  defaultImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  defaultAggregateRating?: AggregateRating;
  companyInfo?: {
    name?: string;
    foundedYear?: number;
    address?: string;
    phone?: string;
    whatsapp?: string;
    email?: string;
    operatingHours?: string;
    totalClients?: number;
    totalProjects?: number;
    serviceAreas?: Array<string>;
    certifications?: Array<string>;
    awards?: Array<string>;
  };
  testimonials?: Array<{
    name?: string;
    position?: string;
    company?: string;
    industry?: string;
    rating?: number;
    quote?: string;
    results?: {
      metric?: string;
      value?: string;
      timeframe?: string;
    };
    date?: string;
    verified?: boolean;
    _key: string;
  }>;
  pricingPackages?: {
    website?: Array<
      {
        _key: string;
      } & PricingPackage
    >;
    software?: Array<
      {
        _key: string;
      } & PricingPackage
    >;
    printing?: Array<
      {
        _key: string;
      } & PricingPackage
    >;
  };
  faq?: {
    website?: Array<
      {
        _key: string;
      } & FaqItem
    >;
    software?: Array<
      {
        _key: string;
      } & FaqItem
    >;
    printing?: Array<
      {
        _key: string;
      } & FaqItem
    >;
  };
};

export type ThemeSettings = {
  _id: string;
  _type: "themeSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  themeColors?: {
    themePreset?:
      | "neutral"
      | "ocean"
      | "sunset"
      | "brand-tricolor-a"
      | "brand-tricolor-b"
      | "brand-tricolor-c";
    lightPrimary?:
      | ""
      | "#171717"
      | "#404040"
      | "#525252"
      | "#EBEBEB"
      | "#F5F5F5"
      | "#FAFAFA"
      | "#0070F3"
      | "#3291FF"
      | "#00A86B"
      | "#14B8A6"
      | "#F59E0B"
      | "#8B5CF6"
      | "#E5484D"
      | "#FB7185";
    lightPrimaryForeground?:
      | ""
      | "#FAFAFA"
      | "#F5F5F5"
      | "#EBEBEB"
      | "#404040"
      | "#171717"
      | "#0A0A0A"
      | "#111111";
    lightAccent?:
      | ""
      | "#171717"
      | "#404040"
      | "#525252"
      | "#EBEBEB"
      | "#F5F5F5"
      | "#FAFAFA"
      | "#0070F3"
      | "#3291FF"
      | "#00A86B"
      | "#14B8A6"
      | "#F59E0B"
      | "#8B5CF6"
      | "#E5484D"
      | "#FB7185";
    lightRing?:
      | ""
      | "#171717"
      | "#404040"
      | "#525252"
      | "#EBEBEB"
      | "#F5F5F5"
      | "#FAFAFA"
      | "#0070F3"
      | "#3291FF"
      | "#00A86B"
      | "#14B8A6"
      | "#F59E0B"
      | "#8B5CF6"
      | "#E5484D"
      | "#FB7185";
    darkPrimary?:
      | ""
      | "#171717"
      | "#404040"
      | "#525252"
      | "#EBEBEB"
      | "#F5F5F5"
      | "#FAFAFA"
      | "#0070F3"
      | "#3291FF"
      | "#00A86B"
      | "#14B8A6"
      | "#F59E0B"
      | "#8B5CF6"
      | "#E5484D"
      | "#FB7185";
    darkPrimaryForeground?:
      | ""
      | "#FAFAFA"
      | "#F5F5F5"
      | "#EBEBEB"
      | "#404040"
      | "#171717"
      | "#0A0A0A"
      | "#111111";
    darkAccent?:
      | ""
      | "#171717"
      | "#404040"
      | "#525252"
      | "#EBEBEB"
      | "#F5F5F5"
      | "#FAFAFA"
      | "#0070F3"
      | "#3291FF"
      | "#00A86B"
      | "#14B8A6"
      | "#F59E0B"
      | "#8B5CF6"
      | "#E5484D"
      | "#FB7185";
    darkRing?:
      | ""
      | "#171717"
      | "#404040"
      | "#525252"
      | "#EBEBEB"
      | "#F5F5F5"
      | "#FAFAFA"
      | "#0070F3"
      | "#3291FF"
      | "#00A86B"
      | "#14B8A6"
      | "#F59E0B"
      | "#8B5CF6"
      | "#E5484D"
      | "#FB7185";
  };
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    dark?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    light?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    width?: number;
    height?: number;
    showBrandName?: boolean;
    brandNameSize?: "sm" | "md" | "lg" | "xl";
  };
  brandName?: string;
  copyright?: BlockContent;
  socialLinks?: Array<{
    platform?:
      | "x"
      | "instagram"
      | "linkedin"
      | "youtube"
      | "facebook"
      | "tiktok"
      | "github"
      | "website";
    url?: string;
    target?: boolean;
    _type: "item";
    _key: string;
  }>;
  whatsApp?: {
    enabled?: boolean;
    phoneNumber?: string;
    predefinedText?: string;
    ctaText?: string;
    enableAnimation?: boolean;
    sourceUrl?: string;
  };
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
  headerCta?: Link;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  title?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: BlockContent;
  rating?: number;
  orderRank?: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: string;
  category?:
    | "general"
    | "website"
    | "software"
    | "support"
    | "printing"
    | "pricing";
  isActive?: "active" | "inactive";
  orderRank?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  meta?: Meta;
  orderRank?: string;
};

export type ServiceType = {
  _id: string;
  _type: "serviceType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  orderRank?: string;
  category?:
    | "software"
    | "percetakan"
    | "pembuatan-website"
    | "sistem-pos"
    | "layanan";
  description?: string;
  defaultTemplate?: PageTemplateReference;
  pricing?: {
    startingPrice?: number;
    currency?: "IDR" | "USD";
    duration?: string;
  };
  sortOrder?: number;
};

export type PageTemplate = {
  _id: string;
  _type: "pageTemplate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  variant?:
    | "service-hero"
    | "local-proof"
    | "pricing-focus"
    | "generic-company";
  lane?: "website" | "software" | "printing" | "generic";
  trustMode?: "safe" | "aggressive";
  sourcePolicy?: TemplateSourcePolicy;
  isHybrid?: boolean;
  shellId?: string;
  topBlockCountDefault?: number;
  heroEyebrow?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  structured?: TemplateRewriteCopy;
  blocks?: Array<
    | ({
        _key: string;
      } & Hero1)
    | ({
        _key: string;
      } & Hero2)
    | ({
        _key: string;
      } & HeroVercel)
    | ({
        _key: string;
      } & StatsHeroBlock)
    | ({
        _key: string;
      } & SectionHeader)
    | ({
        _key: string;
      } & SplitRow)
    | ({
        _key: string;
      } & GridRow)
    | ({
        _key: string;
      } & Carousel1)
    | ({
        _key: string;
      } & Carousel2)
    | ({
        _key: string;
      } & TimelineRow)
    | ({
        _key: string;
      } & Cta1)
    | ({
        _key: string;
      } & WhatsappCta)
    | ({
        _key: string;
      } & LogoCloud1)
    | ({
        _key: string;
      } & Faqs)
    | ({
        _key: string;
      } & FormNewsletter)
    | ({
        _key: string;
      } & AllPosts)
    | ({
        _key: string;
      } & LegacyRichContent)
    | ({
        _key: string;
      } & CompanyInfo)
    | ({
        _key: string;
      } & TestimonialsBlock)
    | ({
        _key: string;
      } & PricingBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & BenefitsBlock)
    | ({
        _key: string;
      } & FeaturesPackageBlock)
    | ({
        _key: string;
      } & ServiceTypesBlock)
    | ({
        _key: string;
      } & ProblemSolutionBlock)
    | ({
        _key: string;
      } & ValuePropsBlock)
  >;
  metaDefaults?: {
    title?: string;
    description?: string;
    canonicalUrl?: string;
    focusKeyword?: string;
    secondaryKeywords?: Array<string>;
    noindex?: boolean;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  orderRank?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  blocks?: Array<
    | ({
        _key: string;
      } & Hero1)
    | ({
        _key: string;
      } & Hero2)
    | ({
        _key: string;
      } & HeroVercel)
    | ({
        _key: string;
      } & StatsHeroBlock)
    | ({
        _key: string;
      } & SectionHeader)
    | ({
        _key: string;
      } & SplitRow)
    | ({
        _key: string;
      } & GridRow)
    | ({
        _key: string;
      } & Carousel1)
    | ({
        _key: string;
      } & Carousel2)
    | ({
        _key: string;
      } & TimelineRow)
    | ({
        _key: string;
      } & Cta1)
    | ({
        _key: string;
      } & WhatsappCta)
    | ({
        _key: string;
      } & LogoCloud1)
    | ({
        _key: string;
      } & Faqs)
    | ({
        _key: string;
      } & FormNewsletter)
    | ({
        _key: string;
      } & AllPosts)
    | ({
        _key: string;
      } & LegacyRichContent)
    | ({
        _key: string;
      } & CompanyInfo)
    | ({
        _key: string;
      } & TestimonialsBlock)
    | ({
        _key: string;
      } & PricingBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & BenefitsBlock)
    | ({
        _key: string;
      } & FeaturesPackageBlock)
    | ({
        _key: string;
      } & ServiceTypesBlock)
    | ({
        _key: string;
      } & ProblemSolutionBlock)
    | ({
        _key: string;
      } & ValuePropsBlock)
  >;
  topBlockCount?: number;
  generator?: GeneratorPageMeta;
  aggregateRating?: AggregateRating;
  meta?: Meta;
  orderRank?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  author?: AuthorReference;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  body?: BlockContent;
  blocks?: Array<
    | ({
        _key: string;
      } & Hero1)
    | ({
        _key: string;
      } & Hero2)
    | ({
        _key: string;
      } & HeroVercel)
    | ({
        _key: string;
      } & StatsHeroBlock)
    | ({
        _key: string;
      } & SectionHeader)
    | ({
        _key: string;
      } & SplitRow)
    | ({
        _key: string;
      } & GridRow)
    | ({
        _key: string;
      } & Carousel1)
    | ({
        _key: string;
      } & Carousel2)
    | ({
        _key: string;
      } & TimelineRow)
    | ({
        _key: string;
      } & Cta1)
    | ({
        _key: string;
      } & WhatsappCta)
    | ({
        _key: string;
      } & LogoCloud1)
    | ({
        _key: string;
      } & Faqs)
    | ({
        _key: string;
      } & FormNewsletter)
    | ({
        _key: string;
      } & AllPosts)
    | ({
        _key: string;
      } & LegacyRichContent)
    | ({
        _key: string;
      } & CompanyInfo)
    | ({
        _key: string;
      } & TestimonialsBlock)
    | ({
        _key: string;
      } & PricingBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & BenefitsBlock)
    | ({
        _key: string;
      } & FeaturesPackageBlock)
    | ({
        _key: string;
      } & ServiceTypesBlock)
    | ({
        _key: string;
      } & ProblemSolutionBlock)
    | ({
        _key: string;
      } & ValuePropsBlock)
  >;
  affiliateItems?: Array<
    {
      _key: string;
    } & AffiliateItem
  >;
  overallRating?: number;
  verdict?: string;
  aggregateRating?: AggregateRating;
  meta?: Meta;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: BlockContent;
  blocks?: Array<
    | ({
        _key: string;
      } & Hero1)
    | ({
        _key: string;
      } & Hero2)
    | ({
        _key: string;
      } & HeroVercel)
    | ({
        _key: string;
      } & StatsHeroBlock)
    | ({
        _key: string;
      } & SectionHeader)
    | ({
        _key: string;
      } & SplitRow)
    | ({
        _key: string;
      } & GridRow)
    | ({
        _key: string;
      } & Carousel1)
    | ({
        _key: string;
      } & Carousel2)
    | ({
        _key: string;
      } & TimelineRow)
    | ({
        _key: string;
      } & Cta1)
    | ({
        _key: string;
      } & WhatsappCta)
    | ({
        _key: string;
      } & LogoCloud1)
    | ({
        _key: string;
      } & Faqs)
    | ({
        _key: string;
      } & FormNewsletter)
    | ({
        _key: string;
      } & AllPosts)
    | ({
        _key: string;
      } & LegacyRichContent)
    | ({
        _key: string;
      } & CompanyInfo)
    | ({
        _key: string;
      } & TestimonialsBlock)
    | ({
        _key: string;
      } & PricingBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & BenefitsBlock)
    | ({
        _key: string;
      } & FeaturesPackageBlock)
    | ({
        _key: string;
      } & ServiceTypesBlock)
    | ({
        _key: string;
      } & ProblemSolutionBlock)
    | ({
        _key: string;
      } & ValuePropsBlock)
  >;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  deliverables?: Array<string>;
  duration?: string;
  startingPrice?: number;
  currency?: "IDR" | "USD" | "EUR";
  featured?: boolean;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  cta?: Link;
  reviews?: Array<
    {
      _key: string;
    } & ReviewItem
  >;
  aggregateRating?: AggregateRating;
  meta?: Meta;
  orderRank?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: BlockContent;
  blocks?: Array<
    | ({
        _key: string;
      } & Hero1)
    | ({
        _key: string;
      } & Hero2)
    | ({
        _key: string;
      } & HeroVercel)
    | ({
        _key: string;
      } & StatsHeroBlock)
    | ({
        _key: string;
      } & SectionHeader)
    | ({
        _key: string;
      } & SplitRow)
    | ({
        _key: string;
      } & GridRow)
    | ({
        _key: string;
      } & Carousel1)
    | ({
        _key: string;
      } & Carousel2)
    | ({
        _key: string;
      } & TimelineRow)
    | ({
        _key: string;
      } & Cta1)
    | ({
        _key: string;
      } & WhatsappCta)
    | ({
        _key: string;
      } & LogoCloud1)
    | ({
        _key: string;
      } & Faqs)
    | ({
        _key: string;
      } & FormNewsletter)
    | ({
        _key: string;
      } & AllPosts)
    | ({
        _key: string;
      } & LegacyRichContent)
    | ({
        _key: string;
      } & CompanyInfo)
    | ({
        _key: string;
      } & TestimonialsBlock)
    | ({
        _key: string;
      } & PricingBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & BenefitsBlock)
    | ({
        _key: string;
      } & FeaturesPackageBlock)
    | ({
        _key: string;
      } & ServiceTypesBlock)
    | ({
        _key: string;
      } & ProblemSolutionBlock)
    | ({
        _key: string;
      } & ValuePropsBlock)
  >;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  price?: number;
  currency?: "IDR" | "USD" | "EUR";
  availability?: "in-stock" | "pre-order" | "out-of-stock";
  featured?: boolean;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  cta?: Link;
  reviews?: Array<
    {
      _key: string;
    } & ReviewItem
  >;
  aggregateRating?: AggregateRating;
  meta?: Meta;
  orderRank?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: BlockContent;
  blocks?: Array<
    | ({
        _key: string;
      } & Hero1)
    | ({
        _key: string;
      } & Hero2)
    | ({
        _key: string;
      } & HeroVercel)
    | ({
        _key: string;
      } & StatsHeroBlock)
    | ({
        _key: string;
      } & SectionHeader)
    | ({
        _key: string;
      } & SplitRow)
    | ({
        _key: string;
      } & GridRow)
    | ({
        _key: string;
      } & Carousel1)
    | ({
        _key: string;
      } & Carousel2)
    | ({
        _key: string;
      } & TimelineRow)
    | ({
        _key: string;
      } & Cta1)
    | ({
        _key: string;
      } & WhatsappCta)
    | ({
        _key: string;
      } & LogoCloud1)
    | ({
        _key: string;
      } & Faqs)
    | ({
        _key: string;
      } & FormNewsletter)
    | ({
        _key: string;
      } & AllPosts)
    | ({
        _key: string;
      } & LegacyRichContent)
    | ({
        _key: string;
      } & CompanyInfo)
    | ({
        _key: string;
      } & TestimonialsBlock)
    | ({
        _key: string;
      } & PricingBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & BenefitsBlock)
    | ({
        _key: string;
      } & FeaturesPackageBlock)
    | ({
        _key: string;
      } & ServiceTypesBlock)
    | ({
        _key: string;
      } & ProblemSolutionBlock)
    | ({
        _key: string;
      } & ValuePropsBlock)
  >;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  clientName?: string;
  industry?: string;
  completionYear?: number;
  projectType?: "portfolio" | "website" | "software" | "repository";
  repositoryUrl?: string;
  previewUrl?: string;
  projectUrl?: string;
  featured?: boolean;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  cta?: Link;
  meta?: Meta;
  orderRank?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  orderRank?: string;
};

export type IconPicker = {
  _type: "iconPicker";
  provider?: string;
  name?: string;
  svg?: string;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Price
  | Meta
  | SanityImageAssetReference
  | MetaImage
  | StatsHeroBlock
  | ValuePropsBlock
  | ProblemSolutionBlock
  | ServiceTypesBlock
  | FeaturesPackageBlock
  | BenefitsBlock
  | PricingBlock
  | TestimonialsBlock
  | FaqBlock
  | CompanyInfo
  | LegacyRichContent
  | AllPosts
  | FormNewsletter
  | FaqReference
  | Faqs
  | LogoCloud1
  | WhatsappCta
  | Cta1
  | Timelines1
  | TimelineRow
  | TestimonialReference
  | Carousel2
  | Carousel1
  | GridRow
  | PostReference
  | GridPost
  | PricingCard
  | GridCard
  | SplitInfo
  | SplitInfoList
  | SplitImage
  | SplitCard
  | SplitCardsList
  | SplitContent
  | SplitRow
  | SectionHeader
  | HeroFeatureCard
  | HeroVercel
  | Hero2
  | Hero1
  | GeneratorProgramReference
  | GeneratorTemplateReference
  | GeneratorDatasetReference
  | GeneratorPageMeta
  | GeneratorRow
  | GeneratorKeywordSet
  | GeneratorTokenDefinition
  | FaqItem
  | PricingPackage
  | TemplateSourcePolicy
  | TemplateRewriteCopy
  | TemplateContentVariant
  | TemplateLongGuide
  | TemplateTestimonial
  | TemplateProofItem
  | TemplateEeatPoint
  | TemplateFeature
  | TemplatePricingPlan
  | TemplateServiceType
  | TemplateFaq
  | TemplateCtaLink
  | AffiliateItem
  | AggregateRating
  | ReviewItem
  | SectionPadding
  | UiIcon
  | NavigationIcon
  | ButtonVariant
  | ColorVariant
  | PageReference
  | CategoryReference
  | ProductReference
  | ServiceReference
  | ProjectReference
  | NavigationLinkChild
  | Link
  | BlockContent
  | ServiceCluster
  | ServiceLane
  | WhyChooseReason
  | HomeContent
  | SanityImageCrop
  | SanityImageHotspot
  | SiteSettings
  | GeneratorProgram
  | GeneratorDataset
  | Slug
  | GeneratorTemplate
  | LegacyPage
  | ReusableSection
  | Redirect
  | SeoOpsSettings
  | ServiceTypeReference
  | LocationReference
  | PageTemplateReference
  | ServiceLocation
  | PageLocation
  | Location
  | OgSettings
  | Color
  | SeoSettings
  | ThemeSettings
  | Settings
  | Navigation
  | Testimonial
  | Faq
  | Category
  | ServiceType
  | PageTemplate
  | Page
  | AuthorReference
  | Post
  | Service
  | Product
  | Project
  | Author
  | IconPicker
  | RgbaColor
  | HsvaColor
  | HslaColor
  | MediaTag
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
